export const articles = [
  {
    category: "Permanent Residence",
    tag: "evergreen",
    title: "Express Entry explained — the complete guide for Nigerians in 2026",
    excerpt: "Everything from creating your profile to receiving your Invitation to Apply. Broken down simply.",
    date: "May 24, 2026",
    read: "12 min",
    color: "#1A6EBD",
    bg: "#EBF4FF",
  },
  {
    category: "Work Permits",
    tag: "evergreen",
    title: "What is LMIA and how does it affect your Canadian work permit?",
    excerpt: "A Labour Market Impact Assessment can make or break your application. Here is everything you need to know.",
    date: "May 21, 2026",
    read: "8 min",
    color: "#0F7B5B",
    bg: "#E6F7F2",
  },
  {
    category: "News",
    tag: "news",
    title: "Express Entry draw — May 2026: 4,500 invitations issued at CRS 491",
    excerpt: "IRCC conducted a new draw this week. Here is what the cutoff means for applicants in the pool.",
    date: "May 27, 2026",
    read: "3 min",
    color: "#B45309",
    bg: "#FEF3C7",
  },
  {
    category: "Life in Canada",
    tag: "evergreen",
    title: "Cost of living in Canada 2026 — what Nigerians need to budget for",
    excerpt: "Realistic monthly expense breakdowns across Toronto, Calgary, Ottawa, and other major cities.",
    date: "May 18, 2026",
    read: "10 min",
    color: "#7C3AED",
    bg: "#F5F3FF",
  },
  {
    category: "Study Permits",
    tag: "evergreen",
    title: "Best Canadian provinces for Nigerian immigrants — honest breakdown",
    excerpt: "Job opportunities, immigration pathways, cost of living — ranked and compared for Nigerians.",
    date: "May 15, 2026",
    read: "9 min",
    color: "#DB2777",
    bg: "#FDF2F8",
  },
  {
    category: "News",
    tag: "news",
    title: "Canada announces new 2027 immigration targets — what it means for you",
    excerpt: "IRCC released updated targets. Here is how the new numbers affect Nigerians in the queue.",
    date: "May 26, 2026",
    read: "5 min",
    color: "#B45309",
    bg: "#FEF3C7",
  },
];

export const categories = [
  {
    icon: "🏠",
    title: "Permanent Residence",
    desc: "Express Entry, PNP, family sponsorship and all PR pathways",
    count: 12,
    color: "#1A6EBD",
    bg: "#EBF4FF",
    guides: [
      "Express Entry explained",
      "CRS score improvement guide",
      "Provincial Nominee Program",
      "Family sponsorship complete guide",
      "PR application checklist 2026",
    ],
  },
  {
    icon: "💼",
    title: "Work Permits",
    desc: "LMIA, open work permits, employer sponsorship and more",
    count: 8,
    color: "#0F7B5B",
    bg: "#E6F7F2",
    guides: [
      "What is LMIA — complete guide",
      "Open vs closed work permit",
      "How to find employers who sponsor",
      "Post-graduation work permit guide",
    ],
  },
  {
    icon: "🎓",
    title: "Study Permits",
    desc: "University applications, study permits and study to PR pathway",
    count: 6,
    color: "#7C3AED",
    bg: "#F5F3FF",
    guides: [
      "How to apply for a study permit",
      "Top universities for Nigerians",
      "Study to PR — the full pathway",
    ],
  },
  {
    icon: "🍁",
    title: "Life in Canada",
    desc: "Cost of living, best provinces, healthcare and community",
    count: 9,
    color: "#B45309",
    bg: "#FEF3C7",
    guides: [
      "Cost of living in Canada 2026",
      "Best provinces for Nigerian immigrants",
      "Healthcare system explained",
      "Nigerian community in Canada",
    ],
  },
];